<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>Terse syntax C# command line parser for .NET with F# support. The Command Line Parser Library offers to CLR applications a clean and concise API for manipulating command line arguments and related tasks.</Description>
    <AssemblyTitle>Command Line Parser Library</AssemblyTitle>
    <Authors>Giacomo Stelluti Scala</Authors>
    <TargetFrameworks>netstandard2.0</TargetFrameworks>
    <DefineConstants>$(DefineConstants);CSX_REM_EITHER_FUNC;SKIP_FSHARP</DefineConstants>
    <AssemblyName>CommandLine</AssemblyName>
    <PackageId>CommandLineParser</PackageId>
    <PackageLicenseUrl>https://raw.githubusercontent.com/gsscoder/commandline/master/doc/LICENSE</PackageLicenseUrl>
    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>https://github.com/gsscoder/commandline</RepositoryUrl>
    <GenerateAssemblyTitleAttribute>false</GenerateAssemblyTitleAttribute>
    <GenerateAssemblyDescriptionAttribute>false</GenerateAssemblyDescriptionAttribute>
    <GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
    <Version>2.1.1.21</Version>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
  </PropertyGroup>
  
</Project>
